// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend_protonum.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	backend_protonum.proto
	protocol.proto

It has these top-level messages:
	Functions
	SignupRequest
	SignupReply
	LoginRequest
	LoginReply
	FollowUnFollowRequest
	FollowUnFollowReply
	AddTweetRequest
	AddTweetReply
	GetFollowingTweetsRequest
	GetFollowingTweetsReply
	Tweet
	Timestamp
	GetUserProfileRequest
	GetUserProfileReply
	MomentRandomFeedsRequest
	MomentRandomFeedsReply
	CheckIfFollowingRequest
	CheckIfFollowingReply
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Functions_FunctionName int32

const (
	Functions_reserve0              Functions_FunctionName = 0
	Functions_reserve1              Functions_FunctionName = 1
	Functions_reserve2              Functions_FunctionName = 2
	Functions_reserve3              Functions_FunctionName = 3
	Functions_reserve4              Functions_FunctionName = 4
	Functions_SignupRPC             Functions_FunctionName = 5
	Functions_LoginRPC              Functions_FunctionName = 6
	Functions_FollowUnFollowRPC     Functions_FunctionName = 7
	Functions_AddTweetRPC           Functions_FunctionName = 8
	Functions_GetFollowingTweetsRPC Functions_FunctionName = 9
	Functions_GetUserProfileRPC     Functions_FunctionName = 10
	Functions_MomentRandomFeedsRPC  Functions_FunctionName = 11
	Functions_CheckIfFollowingRPC   Functions_FunctionName = 12
)

var Functions_FunctionName_name = map[int32]string{
	0:  "reserve0",
	1:  "reserve1",
	2:  "reserve2",
	3:  "reserve3",
	4:  "reserve4",
	5:  "SignupRPC",
	6:  "LoginRPC",
	7:  "FollowUnFollowRPC",
	8:  "AddTweetRPC",
	9:  "GetFollowingTweetsRPC",
	10: "GetUserProfileRPC",
	11: "MomentRandomFeedsRPC",
	12: "CheckIfFollowingRPC",
}
var Functions_FunctionName_value = map[string]int32{
	"reserve0":              0,
	"reserve1":              1,
	"reserve2":              2,
	"reserve3":              3,
	"reserve4":              4,
	"SignupRPC":             5,
	"LoginRPC":              6,
	"FollowUnFollowRPC":     7,
	"AddTweetRPC":           8,
	"GetFollowingTweetsRPC": 9,
	"GetUserProfileRPC":     10,
	"MomentRandomFeedsRPC":  11,
	"CheckIfFollowingRPC":   12,
}

func (x Functions_FunctionName) String() string {
	return proto.EnumName(Functions_FunctionName_name, int32(x))
}
func (Functions_FunctionName) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Functions struct {
}

func (m *Functions) Reset()                    { *m = Functions{} }
func (m *Functions) String() string            { return proto.CompactTextString(m) }
func (*Functions) ProtoMessage()               {}
func (*Functions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Functions)(nil), "protocol.Functions")
	proto.RegisterEnum("protocol.Functions_FunctionName", Functions_FunctionName_name, Functions_FunctionName_value)
}

func init() { proto.RegisterFile("backend_protonum.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x69, 0x81, 0x92, 0x4c, 0x83, 0x30, 0x86, 0xf2, 0xb3, 0xed, 0x01, 0x10, 0x50, 0x2e,
	0x80, 0x2a, 0xa5, 0x42, 0x02, 0x54, 0x15, 0xba, 0x46, 0x69, 0x3c, 0x0d, 0x56, 0x93, 0x99, 0xca,
	0x71, 0xe8, 0x25, 0x38, 0x33, 0x42, 0xe3, 0x08, 0x94, 0xd5, 0xf3, 0xf7, 0x3e, 0xfb, 0x2d, 0x0c,
	0x17, 0xab, 0x2c, 0xdf, 0x20, 0x99, 0x8f, 0xad, 0x63, 0xcf, 0xd4, 0x54, 0x37, 0xe1, 0xa0, 0xa3,
	0x10, 0x39, 0x97, 0xe3, 0xef, 0x3e, 0xc4, 0x69, 0x43, 0xb9, 0xb7, 0x4c, 0xf5, 0xf8, 0xa7, 0x07,
	0xc9, 0x1f, 0xbd, 0x66, 0x15, 0xea, 0x04, 0x22, 0x87, 0x35, 0xba, 0x2f, 0xbc, 0x55, 0x7b, 0x1d,
	0xba, 0x53, 0xbd, 0x0e, 0xdd, 0xab, 0x7e, 0x87, 0x26, 0x6a, 0xbf, 0x43, 0x0f, 0xea, 0x40, 0x1f,
	0x43, 0xfc, 0x66, 0x0b, 0x6a, 0xb6, 0x8b, 0xf9, 0x54, 0x1d, 0x8a, 0x7c, 0xe6, 0xc2, 0x92, 0xd0,
	0x40, 0x8f, 0xe0, 0x34, 0xe5, 0xb2, 0xe4, 0xdd, 0x92, 0xda, 0x94, 0xfa, 0x48, 0x9f, 0xc0, 0xf0,
	0xd1, 0x98, 0xf7, 0x1d, 0xa2, 0x97, 0x22, 0xd2, 0xd7, 0x30, 0x9a, 0xa1, 0x6f, 0xaf, 0x58, 0x2a,
	0x82, 0xa9, 0x45, 0xc5, 0x32, 0x31, 0x43, 0xbf, 0xac, 0xd1, 0xcd, 0x1d, 0xaf, 0x6d, 0x89, 0x52,
	0x83, 0xbe, 0x82, 0xf3, 0x17, 0xae, 0x90, 0xfc, 0x22, 0x23, 0xc3, 0x55, 0x8a, 0x68, 0xc2, 0x83,
	0xa1, 0xbe, 0x84, 0xb3, 0xe9, 0x27, 0xe6, 0x9b, 0xa7, 0xf5, 0xff, 0x9e, 0x88, 0x64, 0x35, 0x08,
	0x1f, 0x33, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x34, 0x7c, 0x40, 0x12, 0x39, 0x01, 0x00, 0x00,
}
