// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	SignupRequest
	SignupReply
	LoginRequest
	LoginReply
	FollowUnFollowRequest
	FollowUnFollowReply
	AddTweetRequest
	AddTweetReply
	GetFollowingTweetsRequest
	GetFollowingTweetsReply
	Tweet
	Timestamp
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignupRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *SignupRequest) Reset()                    { *m = SignupRequest{} }
func (m *SignupRequest) String() string            { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()               {}
func (*SignupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SignupRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignupRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignupReply struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Success  bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *SignupReply) Reset()                    { *m = SignupReply{} }
func (m *SignupReply) String() string            { return proto.CompactTextString(m) }
func (*SignupReply) ProtoMessage()               {}
func (*SignupReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SignupReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignupReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Success  bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type FollowUnFollowRequest struct {
	Username   string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Targetname string `protobuf:"bytes,2,opt,name=targetname" json:"targetname,omitempty"`
}

func (m *FollowUnFollowRequest) Reset()                    { *m = FollowUnFollowRequest{} }
func (m *FollowUnFollowRequest) String() string            { return proto.CompactTextString(m) }
func (*FollowUnFollowRequest) ProtoMessage()               {}
func (*FollowUnFollowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FollowUnFollowRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FollowUnFollowRequest) GetTargetname() string {
	if m != nil {
		return m.Targetname
	}
	return ""
}

type FollowUnFollowReply struct {
	Username   string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Targetname string `protobuf:"bytes,2,opt,name=targetname" json:"targetname,omitempty"`
	Success    bool   `protobuf:"varint,3,opt,name=success" json:"success,omitempty"`
}

func (m *FollowUnFollowReply) Reset()                    { *m = FollowUnFollowReply{} }
func (m *FollowUnFollowReply) String() string            { return proto.CompactTextString(m) }
func (*FollowUnFollowReply) ProtoMessage()               {}
func (*FollowUnFollowReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FollowUnFollowReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FollowUnFollowReply) GetTargetname() string {
	if m != nil {
		return m.Targetname
	}
	return ""
}

func (m *FollowUnFollowReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AddTweetRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Post     string `protobuf:"bytes,2,opt,name=post" json:"post,omitempty"`
}

func (m *AddTweetRequest) Reset()                    { *m = AddTweetRequest{} }
func (m *AddTweetRequest) String() string            { return proto.CompactTextString(m) }
func (*AddTweetRequest) ProtoMessage()               {}
func (*AddTweetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AddTweetRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddTweetRequest) GetPost() string {
	if m != nil {
		return m.Post
	}
	return ""
}

type AddTweetReply struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Success  bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *AddTweetReply) Reset()                    { *m = AddTweetReply{} }
func (m *AddTweetReply) String() string            { return proto.CompactTextString(m) }
func (*AddTweetReply) ProtoMessage()               {}
func (*AddTweetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AddTweetReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddTweetReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetFollowingTweetsRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *GetFollowingTweetsRequest) Reset()                    { *m = GetFollowingTweetsRequest{} }
func (m *GetFollowingTweetsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFollowingTweetsRequest) ProtoMessage()               {}
func (*GetFollowingTweetsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetFollowingTweetsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetFollowingTweetsReply struct {
	Username string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Tweet    []*Tweet `protobuf:"bytes,2,rep,name=tweet" json:"tweet,omitempty"`
	Success  bool     `protobuf:"varint,3,opt,name=success" json:"success,omitempty"`
}

func (m *GetFollowingTweetsReply) Reset()                    { *m = GetFollowingTweetsReply{} }
func (m *GetFollowingTweetsReply) String() string            { return proto.CompactTextString(m) }
func (*GetFollowingTweetsReply) ProtoMessage()               {}
func (*GetFollowingTweetsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetFollowingTweetsReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetFollowingTweetsReply) GetTweet() []*Tweet {
	if m != nil {
		return m.Tweet
	}
	return nil
}

func (m *GetFollowingTweetsReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Tweet struct {
	UserName  string     `protobuf:"bytes,1,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	Timestamp *Timestamp `protobuf:"bytes,2,opt,name=Timestamp,json=timestamp" json:"Timestamp,omitempty"`
	Body      string     `protobuf:"bytes,3,opt,name=Body,json=body" json:"Body,omitempty"`
}

func (m *Tweet) Reset()                    { *m = Tweet{} }
func (m *Tweet) String() string            { return proto.CompactTextString(m) }
func (*Tweet) ProtoMessage()               {}
func (*Tweet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Tweet) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Tweet) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Tweet) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Timestamp struct {
	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds int64 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution. Negative
	// second values with fractions must still have non-negative nanos values
	// that count forward in time. Must be from 0 to 999,999,999
	// inclusive.
	Nanos int32 `protobuf:"varint,2,opt,name=nanos" json:"nanos,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

func init() {
	proto.RegisterType((*SignupRequest)(nil), "protocol.SignupRequest")
	proto.RegisterType((*SignupReply)(nil), "protocol.SignupReply")
	proto.RegisterType((*LoginRequest)(nil), "protocol.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "protocol.LoginReply")
	proto.RegisterType((*FollowUnFollowRequest)(nil), "protocol.FollowUnFollowRequest")
	proto.RegisterType((*FollowUnFollowReply)(nil), "protocol.FollowUnFollowReply")
	proto.RegisterType((*AddTweetRequest)(nil), "protocol.AddTweetRequest")
	proto.RegisterType((*AddTweetReply)(nil), "protocol.AddTweetReply")
	proto.RegisterType((*GetFollowingTweetsRequest)(nil), "protocol.GetFollowingTweetsRequest")
	proto.RegisterType((*GetFollowingTweetsReply)(nil), "protocol.GetFollowingTweetsReply")
	proto.RegisterType((*Tweet)(nil), "protocol.Tweet")
	proto.RegisterType((*Timestamp)(nil), "protocol.Timestamp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TwitterRPC service

type TwitterRPCClient interface {
	SignupRPC(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupReply, error)
	LoginRPC(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	FollowUnFollowRPC(ctx context.Context, in *FollowUnFollowRequest, opts ...grpc.CallOption) (*FollowUnFollowReply, error)
	AddTweetRPC(ctx context.Context, in *AddTweetRequest, opts ...grpc.CallOption) (*AddTweetReply, error)
	GetFollowingTweetsRPC(ctx context.Context, in *GetFollowingTweetsRequest, opts ...grpc.CallOption) (*GetFollowingTweetsReply, error)
}

type twitterRPCClient struct {
	cc *grpc.ClientConn
}

func NewTwitterRPCClient(cc *grpc.ClientConn) TwitterRPCClient {
	return &twitterRPCClient{cc}
}

func (c *twitterRPCClient) SignupRPC(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupReply, error) {
	out := new(SignupReply)
	err := grpc.Invoke(ctx, "/protocol.TwitterRPC/SignupRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twitterRPCClient) LoginRPC(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/protocol.TwitterRPC/LoginRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twitterRPCClient) FollowUnFollowRPC(ctx context.Context, in *FollowUnFollowRequest, opts ...grpc.CallOption) (*FollowUnFollowReply, error) {
	out := new(FollowUnFollowReply)
	err := grpc.Invoke(ctx, "/protocol.TwitterRPC/FollowUnFollowRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twitterRPCClient) AddTweetRPC(ctx context.Context, in *AddTweetRequest, opts ...grpc.CallOption) (*AddTweetReply, error) {
	out := new(AddTweetReply)
	err := grpc.Invoke(ctx, "/protocol.TwitterRPC/AddTweetRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twitterRPCClient) GetFollowingTweetsRPC(ctx context.Context, in *GetFollowingTweetsRequest, opts ...grpc.CallOption) (*GetFollowingTweetsReply, error) {
	out := new(GetFollowingTweetsReply)
	err := grpc.Invoke(ctx, "/protocol.TwitterRPC/GetFollowingTweetsRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TwitterRPC service

type TwitterRPCServer interface {
	SignupRPC(context.Context, *SignupRequest) (*SignupReply, error)
	LoginRPC(context.Context, *LoginRequest) (*LoginReply, error)
	FollowUnFollowRPC(context.Context, *FollowUnFollowRequest) (*FollowUnFollowReply, error)
	AddTweetRPC(context.Context, *AddTweetRequest) (*AddTweetReply, error)
	GetFollowingTweetsRPC(context.Context, *GetFollowingTweetsRequest) (*GetFollowingTweetsReply, error)
}

func RegisterTwitterRPCServer(s *grpc.Server, srv TwitterRPCServer) {
	s.RegisterService(&_TwitterRPC_serviceDesc, srv)
}

func _TwitterRPC_SignupRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterRPCServer).SignupRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.TwitterRPC/SignupRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterRPCServer).SignupRPC(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwitterRPC_LoginRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterRPCServer).LoginRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.TwitterRPC/LoginRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterRPCServer).LoginRPC(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwitterRPC_FollowUnFollowRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUnFollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterRPCServer).FollowUnFollowRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.TwitterRPC/FollowUnFollowRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterRPCServer).FollowUnFollowRPC(ctx, req.(*FollowUnFollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwitterRPC_AddTweetRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterRPCServer).AddTweetRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.TwitterRPC/AddTweetRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterRPCServer).AddTweetRPC(ctx, req.(*AddTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwitterRPC_GetFollowingTweetsRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingTweetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterRPCServer).GetFollowingTweetsRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.TwitterRPC/GetFollowingTweetsRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterRPCServer).GetFollowingTweetsRPC(ctx, req.(*GetFollowingTweetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TwitterRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.TwitterRPC",
	HandlerType: (*TwitterRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignupRPC",
			Handler:    _TwitterRPC_SignupRPC_Handler,
		},
		{
			MethodName: "LoginRPC",
			Handler:    _TwitterRPC_LoginRPC_Handler,
		},
		{
			MethodName: "FollowUnFollowRPC",
			Handler:    _TwitterRPC_FollowUnFollowRPC_Handler,
		},
		{
			MethodName: "AddTweetRPC",
			Handler:    _TwitterRPC_AddTweetRPC_Handler,
		},
		{
			MethodName: "GetFollowingTweetsRPC",
			Handler:    _TwitterRPC_GetFollowingTweetsRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol.proto",
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x65, 0xeb, 0x0a, 0xcd, 0x0d, 0x63, 0xc2, 0x5b, 0x69, 0x16, 0x09, 0x18, 0x46, 0x48, 0x7b,
	0x9a, 0x44, 0x79, 0x40, 0x02, 0xf1, 0xb0, 0x59, 0x6c, 0x2f, 0x08, 0x45, 0x5e, 0xfb, 0x01, 0x59,
	0x62, 0x45, 0x81, 0xd4, 0x0e, 0xb1, 0x43, 0x94, 0x1f, 0xe0, 0xbb, 0x51, 0xec, 0xa6, 0xc9, 0xb2,
	0xac, 0xad, 0xb6, 0xa7, 0xf8, 0xe6, 0x1c, 0x9f, 0x73, 0xae, 0x75, 0x2f, 0xbc, 0x48, 0x33, 0xa1,
	0x44, 0x20, 0x92, 0x33, 0x7d, 0x40, 0xa3, 0xba, 0xc6, 0x57, 0xb0, 0x7f, 0x1d, 0x47, 0x3c, 0x4f,
	0x29, 0xfb, 0x93, 0x33, 0xa9, 0x90, 0x0b, 0xa3, 0x5c, 0xb2, 0x8c, 0xfb, 0x0b, 0xe6, 0xec, 0x9c,
	0xec, 0x9c, 0x5a, 0x74, 0x55, 0x57, 0x58, 0xea, 0x4b, 0x59, 0x88, 0x2c, 0x74, 0x76, 0x0d, 0x56,
	0xd7, 0x98, 0x80, 0x5d, 0x0b, 0xa5, 0x49, 0xb9, 0x56, 0xc6, 0x81, 0x67, 0x32, 0x0f, 0x02, 0x26,
	0xa5, 0x56, 0x19, 0xd1, 0xba, 0xc4, 0x97, 0xf0, 0xfc, 0x87, 0x88, 0x62, 0xfe, 0xd8, 0x30, 0x17,
	0x00, 0x4b, 0x9d, 0x87, 0x67, 0xb9, 0x86, 0xf1, 0xa5, 0x48, 0x12, 0x51, 0xcc, 0xb9, 0xf9, 0x6e,
	0x13, 0xea, 0x0d, 0x80, 0xf2, 0xb3, 0x88, 0x29, 0x8d, 0x9a, 0x58, 0xad, 0x3f, 0xf8, 0x37, 0x1c,
	0x76, 0x45, 0x37, 0x25, 0xdc, 0x20, 0xd9, 0xee, 0x60, 0x70, 0xbb, 0x83, 0x73, 0x38, 0x38, 0x0f,
	0xc3, 0x59, 0xc1, 0x98, 0xda, 0x26, 0x3b, 0x82, 0xbd, 0x54, 0x48, 0xb5, 0xb4, 0xd0, 0x67, 0xfc,
	0x1d, 0xf6, 0x1b, 0x89, 0x87, 0xbf, 0xe5, 0x67, 0x38, 0xbe, 0x62, 0xca, 0x74, 0x1c, 0xf3, 0x48,
	0xeb, 0xc9, 0x2d, 0x32, 0xe1, 0xbf, 0x30, 0xe9, 0xbb, 0xb8, 0x29, 0xc9, 0x07, 0x18, 0xaa, 0x8a,
	0xea, 0xec, 0x9e, 0x0c, 0x4e, 0xed, 0xe9, 0xc1, 0xd9, 0x6a, 0xfe, 0x4d, 0x2b, 0x06, 0x5d, 0xf3,
	0x74, 0xbf, 0x60, 0xa8, 0x99, 0x95, 0xcb, 0x5c, 0xb2, 0xec, 0x67, 0xc7, 0xa5, 0xaa, 0xd1, 0x47,
	0xb0, 0x66, 0xf1, 0x82, 0x49, 0xe5, 0x2f, 0x52, 0xdd, 0xb1, 0x3d, 0x3d, 0x6c, 0x39, 0xd5, 0x10,
	0xb5, 0x54, 0x7d, 0xac, 0xde, 0xf8, 0x42, 0x84, 0xa5, 0xb6, 0xb3, 0xe8, 0xde, 0x8d, 0x08, 0x4b,
	0xfc, 0xb5, 0x25, 0xa3, 0x23, 0xb1, 0x40, 0xf0, 0x50, 0x6a, 0xbb, 0x01, 0xad, 0x4b, 0x74, 0x04,
	0x43, 0xee, 0x73, 0x61, 0xde, 0x76, 0x48, 0x4d, 0x31, 0xfd, 0x37, 0x00, 0x98, 0x15, 0xb1, 0x52,
	0x2c, 0xa3, 0x1e, 0x41, 0xdf, 0xc0, 0x5a, 0x6e, 0xa1, 0x47, 0xd0, 0xa4, 0x09, 0x73, 0x6b, 0xc7,
	0xdd, 0xf1, 0x5d, 0x20, 0x4d, 0x4a, 0xfc, 0x04, 0x7d, 0x81, 0x91, 0xd9, 0x1b, 0x8f, 0xa0, 0x57,
	0x0d, 0xa9, 0xbd, 0x93, 0xee, 0xd1, 0x9d, 0xff, 0xe6, 0xee, 0x1c, 0x5e, 0x76, 0x46, 0xdb, 0x23,
	0xe8, 0x6d, 0x43, 0xee, 0x5d, 0x26, 0xf7, 0xf5, 0xfd, 0x04, 0x23, 0x4b, 0xc0, 0x5e, 0x4d, 0xa0,
	0x47, 0xd0, 0x71, 0xc3, 0xef, 0xcc, 0xb6, 0x3b, 0xe9, 0x83, 0x8c, 0x88, 0x0f, 0xe3, 0x9e, 0x31,
	0xf2, 0x08, 0x7a, 0xdf, 0xdc, 0xb9, 0x77, 0x40, 0xdd, 0x77, 0xeb, 0x49, 0xda, 0xe2, 0xe6, 0xa9,
	0xe6, 0x7c, 0xfa, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xac, 0xac, 0x6c, 0x16, 0x6b, 0x05, 0x00, 0x00,
}
